environment:
  isaac:
    headless: true
    sim_device: cuda:0
    pipeline: gpu
    physics_engine: physx
    graphics_device_id: 0
    num_threads: 0
    solver_type: 1
    num_subscenes: 4
    decimation: 5
    torque_delay: 0.005
    sim:
      dt: 0.005
      substeps: 1
      up_axis: z
      use_gpu_pipeline: true
      gravity:
      - 0.0
      - 0.0
      - -9.81
      physx:
        use_gpu: true
        num_threads: 0
        solver_type: 1
        num_position_iterations: 4
        num_velocity_iterations: 0
        contact_offset: 0.01
        rest_offset: 0.0
        bounce_threshold_velocity: 0.1
        max_depenetration_velocity: 100.0
        default_buffer_size_multiplier: 5.0
        max_gpu_contact_pairs: 8388608
        num_subscenes: 4
        contact_collection: 2
  assets:
    simha:
      cls: isaac_base
      file: resources/robots/happybot_sim2real/urdf/happy.urdf
      force_sensors:
      - foot
      asset_options:
        disable_gravity: false
        collapse_fixed_joints: true
        fix_base_link: false
        default_dof_drive_mode: 3
        replace_cylinder_with_capsule: true
        flip_visual_attachments: false
        density: 0.001
        angular_damping: 0.0
        linear_damping: 0.0
        max_angular_velocity: 1000.0
        max_linear_velocity: 1000.0
        armature: 0.0
        thickness: 0.01
        vhacd_enabled: true
      self_collisions: 0
      forward_vec:
      - 1.0
      - 0.0
      - 0.0
      armatures:
        left_hip_yaw: 0.012
        left_hip_roll: 0.012
        left_hip_pitch: 0.017
        left_knee: 0.024
        left_ankle_pitch: 0.024
        left_ankle_roll: 0.01
        right_hip_yaw: 0.012
        right_hip_roll: 0.012
        right_hip_pitch: 0.017
        right_knee: 0.024
        right_ankle_pitch: 0.024
        right_ankle_roll: 0.01
        torso_tilt: 0.012
        torso_pitch: 0.01
        torso_yaw: 0.01
      init_state:
        pos:
        - 0.0
        - 0.0
        - 0.92
        rot:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        lin_vel:
        - 0.0
        - 0.0
        - 0.0
        ang_vel:
        - 0.0
        - 0.0
        - 0.0
        default_joint_angles:
          left_hip_yaw: 0.0
          left_hip_roll: 0.0
          left_hip_pitch: 0.0
          left_knee: 0.0
          left_ankle_pitch: 0.0
          left_ankle_roll: 0.0
          right_hip_yaw: 0.0
          right_hip_roll: 0.0
          right_hip_pitch: 0.0
          right_knee: 0.0
          right_ankle_pitch: 0.0
          right_ankle_roll: 0.0
          torso_tilt: 0.0
          torso_pitch: 0.0
        default_joint_angles_init:
          left_hip_yaw: 0.0
          left_hip_roll: -0.148
          left_hip_pitch: 0.0
          left_knee: 0.0
          left_ankle_pitch: -0.48
          left_ankle_roll: 0.0
          right_hip_yaw: 0.0
          right_hip_roll: 0.148
          right_hip_pitch: 0.0
          right_knee: 0.0
          right_ankle_pitch: 0.48
          right_ankle_roll: 0.0
          torso_tilt: 0.0
          torso_pitch: 0.0
      joints_limits:
        soft_dof_pos_limit: 1.0
        soft_dof_vel_limit: 1.0
  cls: simha_train_isaac_standing
  env:
    num_envs: 4096
    num_actions: 15
    robot_asset: simha
  viewer:
    ref_env: 0
    pos:
    - 0
    - 0
    - 6
    lookat:
    - 0.0
    - 5
    - 3.0
terrains:
  train:
    name: grid
    params:
      num_robots: 4096
      mesh_type: trimesh
      horizontal_scale: 0.1
      vertical_scale: 0.005
      border_size: 25
      curriculum: true
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
      measure_heights: true
      measured_points_x:
      - -0.5
      - -0.4
      - -0.3
      - -0.2
      - -0.1
      - 0.0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      measured_points_y:
      - -0.5
      - -0.4
      - -0.3
      - -0.2
      - -0.1
      - 0.0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      selected: false
      evaluation: false
      terrain_kwargs: None
      max_init_terrain_level: 5
      terrain_length: 8.0
      terrain_width: 8.0
      num_rows: 10
      num_cols: 20
      terrain_proportions:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      slope_treshold: 0.75
pods:
  standing:
    cls: standing_simha_v2
    env:
      num_observations: 41
      num_privileged_obs: null
    control:
      visible_dofs:
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee
      - left_ankle_pitch
      - left_ankle_roll
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle_pitch
      - right_ankle_roll
      fixed_dofs:
      - torso_yaw
      - torso_pitch
      - torso_tilt
      control_type: P
      kp:
        hip_yaw: 100.0
        hip_roll: 100.0
        hip_pitch: 100
        knee: 100.0
        ankle_pitch: 30.0
        ankle_roll: 30.0
      kd:
        hip_yaw: 2.5
        hip_roll: 2.5
        hip_pitch: 2.5
        knee: 2.5
        ankle_pitch: 2.5
        ankle_roll: 2.5
      max_kp:
        hip_yaw: 500.0
        hip_roll: 500.0
        hip_pitch: 500
        knee: 500
        ankle_pitch: 20
        ankle_roll: 20
      max_kd:
        hip_yaw: 5.0
        hip_roll: 5.0
        hip_pitch: 5.0
        knee: 5.0
        ankle_pitch: 5.0
        ankle_roll: 5.0
      min_kp:
        hip_yaw: 50.0
        hip_roll: 50.0
        hip_pitch: 20
        knee: 20
        ankle_pitch: 20
        ankle_roll: 20
      min_kd:
        hip_yaw: 1.0
        hip_roll: 1.0
        hip_pitch: 0.5
        knee: 0.5
        ankle_pitch: 5.0
        ankle_roll: 5.0
      learned_pd: false
      action_scale: 1.0
    commands:
      num_commands: 3
      ranges:
        lin_vel_x:
        - 0.0
        - 0.0
        lin_vel_y:
        - -0.0
        - 0.0
        ang_vel_yaw:
        - 0.0
        - 0.0
      defauls:
        lin_vel_x: 0.0
        lin_vel_y: 0.0
        ang_vel_yaw: 0.0
    normalization:
      clip_observations: 100.0
      clip_actions: true
    phase:
      cycle_duration: 1.0
      phase: 0
      phase_add: 1
      coeff:
      - 1
      - -1
      ratio:
      - 1.0
      - 0.0
      period_shift:
      - 0.0
      - 0.5
      std:
      - 0.1
      - 0.1
    observations:
      pelvis_quat:
        function: get_rigid_body_state
        params:
          names:
          - base_link
          state: rot
          qri: false
        obs_scale: 8.0
      pelvis_ang_v:
        function: get_rigid_body_state
        params:
          names:
          - base_link
          state: ang_vel
          qri: true
        obs_scale: 0.5
      pelvis_lin_acc:
        function: get_lin_acc
        obs_scale: 1.0
      projected_gravity:
        function: get_projected_gravity
        obs_scale: 5.0
      delta_dof:
        function: get_delta_dof
        obs_scale: 4.0
      dof_vel:
        function: get_dof_state
        params:
          state: vel
        obs_scale: 1.0
  upper_body:
    cls: upper_body
    env:
      num_observations: 0
      num_privileged_obs: null
    control:
      visible_dofs:
      - torso_tilt
      - torso_pitch
      control_type: P
      kp:
        torso_tilt: 100.0
        torso_pitch: 100.0
        torso_yaw: 100.0
      kd:
        torso_tilt: 3.0
        torso_pitch: 3.0
        torso_yaw: 3.0
      max_kp:
        torso_tilt: 500.0
        torso_pitch: 500.0
        torso_yaw: 500.0
      max_kd:
        torso_tilt: 5.0
        torso_pitch: 5.0
        torso_yaw: 5.0
      action_scale: 1.0
    normalization:
      clip_observations: 100.0
      clip_actions: 100.0
play:
  environment:
    env:
      num_envs: 1
    isaac:
      headless: false
      camera_follow: true
    domain_rand:
      randomize_friction: false
  domain_rand:
    commands:
      resampling_time: 100000.0
      curriculum:
        use_curriculum: true
    terrain:
      terrain_proportions:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    randomize_friction: false
    friction_range:
    - 0.0
    - 1.5
    randomize_base_mass: false
    added_mass_range:
    - 0.9
    - 1.1
    resample_dof_props_time: 100
    randomize_dof_damping: false
    random_damping_range:
    - 0.0
    - 0.1
    randomize_dof_armature: false
    random_armature_range:
    - 0.0
    - 0.05
    randomize_dof_friction: false
    random_friction_range:
    - 0.0
    - 0.4
    push_robots: true
    push_interval_s: 5
    max_push_vel_xy: 0.5
    observation_noise_range:
    - 1.0
    - 1.0
    obs_single_drop_prob: 0.0
    action_single_drop_prob: 0.0
    group_drop_prob: 0.2
    bus_groups:
    - - left_hip_yaw
      - left_hip_pitch
      - left_hip_roll
    - - right_hip_yaw
      - right_hip_pitch
      - right_hip_roll
    - - left_knee
      - left_ankle_pitch
      - left_ankle_roll
    - - right_knee
      - right_ankle_pitch
      - right_ankle_roll
    - - torso_yaw
      - torso_pitch
      - torso_roll
    dof_pos: 0.1
    dof_vel: 0.1
  algorithm:
    params:
      episode_length_s: 1000
  terrains:
    train:
      params:
        curriculum: false
        num_rows: 1
        num_cols: 1
        terrain_length: 10.0
        terrain_width: 10.0
  predict:
    batch_size: 1
  experiment:
    name: play
    checkname: play
    resume:
      path: /data/experiments/tom/run/standing/all_rands_0.005_trq_lin_acc/experiment_0/last.pth.tar
  play_preferences:
    mode: profile
    profiles_path: /home/tom/PycharmProjects/mentor/projects/walking_simha/utils/short_profile
    save_data: true
    show_figs: false
    save_figs: true
    record_movie: false
    upload_movie: false
    torque_steps: 500
    override_train_config: true
    logger:
      save_log: false
      plot_log: false
      log_path: /home/tom/sim2real_logs
      log_name: test.json
      stop_state_log: 400
      joint_plot:
      - left-hip-pitch
      - left-knee
      - right-hip-pitch
      - right-knee
  rewards:
    standing:
      eval_foot_frc_stance:
        scale: 0.25
        params:
          desired_max_foot_frc: 30
      eval_foot_frc_swing:
        scale: 0.25
        params:
          desired_max_foot_frc: 5
      eval_foot_vel_stance:
        scale: 0.25
        params:
          desired_max_foot_vel: 0.5
      eval_foot_vel_swing:
        scale: 0.25
        params:
          desired_max_foot_vel: 1.0
      eval_base_height:
        scale: 0.15
        params:
          base_height_target: 0.92
      eval_base_orient:
        scale: 0.35
      eval_tracking_lin_vel:
        scale: 0.4
        params:
          tracking_sigma: 10.0
      eval_tracking_ang_vel:
        scale: 0.3
        params:
          tracking_sigma: 10.0
      eval_lower_dof_pos_limits:
        scale: 0.1
      eval_lower_torques:
        scale: 0.07
      eval_lower_torque_limits:
        scale: 0.07
        params:
          soft_torque_limit: 0.9
      eval_dof_acc:
        scale: 0.1
      eval_sym_foot_height:
        scale: 0.3
        params:
          sigma: 5.0
      eval_sym_foot_dist:
        scale: 0.2
        params:
          sigma: 2.0
      eval_torques_diff:
        scale: 0.2
        params:
          sigma: 0.001
extra_dirs:
- stable
rl_backend: isaac
algorithm:
  name: ppo
  params:
    num_steps_per_env: 48
    num_learning_epochs: 4
    num_mini_batches: 4
    clip_param: 0.2
    learning_rate: 0.0001
    schedule: adaptive
    gamma: 0.99
    lam: 0.95
    value_loss_coef: 1.0
    entropy_coef: 0.01
    max_grad_norm: 1.0
    use_clipped_value_loss: true
    desired_kl: 0.01
    init_at_random_ep_len: true
    episode_length_s: 20
    send_timeouts: true
    mirror_loss: 0.0
models:
  main:
    name: actor_critic_rnn
    num_actor_obs: 41
    num_critic_obs: 41
    num_actions: 12
    actor_hidden_dims:
    - 512
    - 256
    - 128
    critic_hidden_dims:
    - 512
    - 256
    - 128
    activation: elu
    init_noise_std: 0.5
    rnn_type: lstm
    rnn_hidden_size: 512
    rnn_num_layers: 2
    normalize_input: false
    tanh_output: true
    learned_pd: false
    num_gains: 6
domain_rand:
  terrain:
    terrain_proportions:
    - 0.8
    - 0.2
    - 0.0
    - 0.0
    - 0.0
  randomize_friction: true
  friction_range:
  - 0.5
  - 1.5
  randomize_base_mass: true
  added_mass_range:
  - 0.9
  - 1.1
  resample_torque_delay_time: 20
  random_torque_delay_range:
  - -2
  - 2
  resample_dof_props_time: 100
  randomize_dof_damping: true
  random_damping_range:
  - 0.0
  - 0.1
  randomize_dof_armature: true
  random_armature_range:
  - 0.0
  - 0.05
  randomize_dof_friction: true
  random_friction_range:
  - 0.0
  - 0.4
  push_robots: true
  push_interval_s: 5
  max_push_vel_xy: 0.5
  observation_noise_range:
  - 0.9
  - 1.1
  obs_single_drop_prob: 0.1
  action_single_drop_prob: 0.1
  group_drop_prob: 0.2
  bus_groups:
  - - left_hip_yaw
    - left_hip_pitch
    - left_hip_roll
  - - right_hip_yaw
    - right_hip_pitch
    - right_hip_roll
  - - left_knee
    - left_ankle_pitch
    - left_ankle_roll
  - - right_knee
    - right_ankle_pitch
    - right_ankle_roll
  - - torso_yaw
    - torso_pitch
    - torso_roll
  dof_pos: 0.1
  dof_vel: 0.1
  commands:
    heading_command: false
    resampling_time: 10.0
    curriculum:
      use_curriculum: false
      lin_vel_threshold: 0.7
      ang_vel_threshold: 0.3
      min_resampling_time: 5.0
      ranges:
        extreme_lin_vel_x:
        - -0.0
        - 0.0
        extreme_ang_vel_yaw:
        - -0.0
        - 0.0
terminations:
  terminate_after_contacts_on:
  - knee
  - base_link
rewards:
  standing:
    dof_no_vel:
      scale: 0.7
      params:
        sigma: 0.02
    rigid_no_vel:
      scale: 0.7
      params:
        sigma: 0.1
    default_stance:
      scale: 0.6
      params:
        sigma: 1.0
    base_orient:
      scale: 0.3
    lower_torques:
      scale: 0.2
    torques_diff:
      scale: 0.2
      params:
        sigma: 0.0001
    termination:
      scale: -2.0
    actions_diff_pos:
      scale: 0.2
      params:
        sigma: 0.01
        max_diff: 100
training:
  epochs: 500
  max_iterations: 30000
  batch_size: 1
  grad_clip: 1.0
  optimizer:
    name: Adam
    params:
      lr: 0.0001
  manual_seed: 2766
experiment:
  location: local
  name: standing
  output_dir: /data/experiments
  checkname: all_rands_0.005_trq_lin_acc_48
  use_username: true
launcher:
  name: ppo
  amp: false
  verbose: true
  val_interval: 1
  save_interval_epoch: 50
  save_interval_batch: 10
  tensorboard:
    train:
      scalar_interval: 1
      vis_interval: 50
      scalars: true
      vis: true
  metrics:
    maxwell_ibc:
      name: MSELoss
user_dir: projects/walking_simha
world_size: 1
device_id: 0
batch_size: 1
device: cuda
