joint_params:
  - name: 'left_hip_yaw'
    min_position: -0.3
    max_position: 1.1
    init_pos: 0.0
    max_velocity: 6
    max_effort: 26
    can_id: 9
    can_socket: 'can7'

  - name: 'left_hip_roll'
    min_position: -0.3
    max_position: 1.1
    init_pos: 0.0
    max_velocity: 6
    max_effort: 26
    can_id: 9
    can_socket: 'can7'
    motor_type: 'AK80_64_V2'