setup_flags:
  have_torse: True

communication:
  frequency: 40 #Hz
  sleep_time_between_motors: 0.0

robot_config:
  robot_name: '/simha'

joints_params:
  left_hip_yaw:
    name: "left_hip_yaw"
    min_position: -0.21
    max_position: 0.21
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 5
    can_socket: 'can6'
    motor_type: 'AK70_10'

  left_hip_roll:
    name: "left_hip_roll"
    min_position: -0.37
    max_position: 0.37
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 7
    can_socket: 'can6'
    motor_type: 'AK70_10'

  left_hip_pitch:
    name: "left_hip_pitch"
    min_position: -0.92
    max_position: 0.92
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 3
    can_socket: 'can6'
    motor_type: 'AK80_64_V3'

  left_knee:
    name: "left_knee"
    min_position: -0.87
    max_position: 0.87
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 8
    can_socket: 'can5'
    motor_type: 'AK80_64_V3'

  left_ankle_pitch:
    name: "left_ankle_pitch"
    min_position: -0.61
    max_position: 0.61
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 6
    can_socket: 'can5'
    motor_type: 'AK80_64_V3'

  left_ankle_roll:
    name: "left_ankle_roll"
    min_position: -0.35
    max_position: 0.35
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 10
    can_socket: 'can5'
    motor_type: 'AK60_6_V2'

  right_hip_yaw:
    name: "right_hip_yaw"
    min_position: -0.21
    max_position: 0.21
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 15
    can_socket: 'can8'
    motor_type: 'AK70_10'

  right_hip_roll:
    name: "right_hip_roll"
    min_position: -0.37
    max_position: 0.37
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 17
    can_socket: 'can8'
    motor_type: 'AK70_10'

  right_hip_pitch:
    name: "right_hip_pitch"
    min_position: -0.92
    max_position: 0.92
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 13
    can_socket: 'can8'
    motor_type: 'AK80_64_V3'

  right_knee:
    name: "right_knee"
    min_position: -0.87
    max_position: 0.87
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 18
    can_socket: 'can7'
    motor_type: 'AK80_64_V3'

  right_ankle_pitch:
    name: "right_ankle_pitch"
    min_position: -0.61
    max_position: 0.61
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 16
    can_socket: 'can7'
    motor_type: 'AK80_64_V3'

  right_ankle_roll:
    name: "right_ankle_roll"
    min_position: -0.35
    max_position: 0.35
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 20
    can_socket: 'can7'
    motor_type: 'AK60_6_V2'

  torso_tilt:
    name: "torso_tilt"
    min_position: -0.0
    max_position: 0.0
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 1
    can_socket: 'can9'
    motor_type: 'AK80_64_V2'

  torso_pitch:
    name: "torso_pitch"
    min_position: -0.0
    max_position: 0.0
    init_pos: 0
    max_velocity: 6
    max_effort: 26
    can_id: 1
    can_socket: 'can9'
    motor_type: 'AK80_64_V2'


